// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiZMH8bFaPsgJcmmc1piB-YVJEeU6VbWs',
    appId: '1:167832364896:web:90b4d1e14618b33db6a005',
    messagingSenderId: '167832364896',
    projectId: 'hadja-store',
    authDomain: 'hadja-store.firebaseapp.com',
    storageBucket: 'hadja-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj68lu_WLSWGClCq9FE5kpPkDU4qFjW30',
    appId: '1:167832364896:android:a7782b2b31a9c3cdb6a005',
    messagingSenderId: '167832364896',
    projectId: 'hadja-store',
    storageBucket: 'hadja-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOBvMWLzf1Fh7SR30KTqKGkRA5hez3t8',
    appId: '1:167832364896:ios:49a20f95b3e7ded6b6a005',
    messagingSenderId: '167832364896',
    projectId: 'hadja-store',
    storageBucket: 'hadja-store.firebasestorage.app',
    iosBundleId: 'com.example.hadjaGrish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHOBvMWLzf1Fh7SR30KTqKGkRA5hez3t8',
    appId: '1:167832364896:ios:49a20f95b3e7ded6b6a005',
    messagingSenderId: '167832364896',
    projectId: 'hadja-store',
    storageBucket: 'hadja-store.firebasestorage.app',
    iosBundleId: 'com.example.hadjaGrish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiZMH8bFaPsgJcmmc1piB-YVJEeU6VbWs',
    appId: '1:167832364896:web:638a1dab5d2845d2b6a005',
    messagingSenderId: '167832364896',
    projectId: 'hadja-store',
    authDomain: 'hadja-store.firebaseapp.com',
    storageBucket: 'hadja-store.firebasestorage.app',
  );
}
